apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fc9x8s8dj-python
  janus-idp.io/tekton: fc9x8s8dj-python
  backstage.io/kubernetes-id: fc9x8s8dj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fc9x8s8dj-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
