apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: fc9x8s8dj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fc9x8s8dj-python 
  name: fc9x8s8dj-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fc9x8s8dj-python
    weight: 100 
