apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fc9x8s8dj-python-gitops
  description: This is GitOps manifest for fc9x8s8dj-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: fc9x8s8dj-python
    janus-idp.io/tekton: fc9x8s8dj-python 
    backstage.io/kubernetes-id: fc9x8s8dj-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fc9x8s8dj-python
